version: '3.8'

services:
  orchestrator:
    build: .
    container_name: llm_orchestrator
    ports:
      - "8080:8080"
    environment:
      - ENV=prod
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    
  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - orchestrator
    restart: unless-stopped
    profiles:
      - with-proxy
